#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running lint-staged..."
pnpm lint-staged

if [ $? -ne 0 ]; then
  echo "Lint-staged failed. Aborting commit/push."
  exit 1
fi

echo "Running pnpm build..."
pnpm build

if [ $? -ne 0 ]; then
  echo "Build failed. Aborting commit/push."
  exit 1
fi

echo "All checks passed. Proceeding with commit/push."