#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

. "$(dirname -- "$0")/utils.sh"

_echo "Running lint-staged..."
pnpm lint-staged

if [ $? -ne 0 ]; then
  _echo "Lint-staged failed. Aborting commit."
  exit 1
fi

_echo "Running pnpm build..."
pnpm build

if [ $? -ne 0 ]; then
  _echo "Build failed. Aborting commit."
  exit 1
fi

_echo "All checks passed. Proceeding with commit."
